[CmdletBinding()]param([Parameter(Mandatory)][string]$GodotBin,[Parameter(Mandatory)][string]$ExpectedHead,[Parameter(Mandatory)][string]$ExpectedTree,[string]$EvidenceDir='',[string]$PythonBin='python')
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;if($PSVersionTable.PSVersion.Major-lt 7){throw 'PowerShell 7 required'};$Root=$PSScriptRoot;Set-Location $Root;$GodotBin=(Resolve-Path $GodotBin).Path;if(!$EvidenceDir){$EvidenceDir=Join-Path $Root ('artifacts/r55-'+[guid]::NewGuid().ToString('N'))};$Out=[IO.Path]::GetFullPath($EvidenceDir);if(Test-Path $Out){if(@(Get-ChildItem $Out -Force).Count){throw 'Evidence directory must be empty'}}else{New-Item -ItemType Directory $Out -Force|Out-Null};$env:GODOT_SILENCE_ROOT_WARNING='1';$env:BREAKPOINT_RUNTIME_DISABLED='1';$Utf8=[Text.UTF8Encoding]::new($false);$Fatal='SCRIPT ERROR|Parse Error|Compile Error|Invalid call|Invalid access|ERROR:'
function GitText([string[]]$A){$t=&git @A;if($LASTEXITCODE-ne 0){throw 'git failed'};return(($t-join"`n").Trim())}
function Identity([string]$N){if(GitText @('status','--porcelain=v1','--untracked-files=no')){throw 'TRACKED_TREE_DIRTY'};$h=GitText @('rev-parse','HEAD');$t=GitText @('rev-parse','HEAD^{tree}');if($h-cne$ExpectedHead-or$t-cne$ExpectedTree){throw 'SUBJECT_IDENTITY_MISMATCH'};$v=((&$GodotBin --version)-join"`n").Trim();$s=(Get-FileHash $GodotBin -Algorithm SHA256).Hash.ToLowerInvariant();if($v-cne'4.7.1.stable.double.custom_build.a13da4feb'){throw 'GODOT_VERSION_MISMATCH'};if($s-cne'3633c3e609c8ce2f9bae334a9c7e75c7f974de3af0415ab4a8050a625a15a7a5'){throw 'GODOT_SHA_MISMATCH'};[IO.File]::WriteAllLines((Join-Path $Out $N),@("HEAD=$h","TREE=$t","GODOT_VERSION=$v","GODOT_SHA256=$s"),$Utf8)}
function RunG([string]$N,[string[]]$A){$i=[Diagnostics.ProcessStartInfo]::new();$i.FileName=$GodotBin;$i.WorkingDirectory=$Root;$i.UseShellExecute=$false;$i.RedirectStandardOutput=$true;$i.RedirectStandardError=$true;$i.StandardOutputEncoding=$Utf8;$i.StandardErrorEncoding=$Utf8;foreach($x in(@('--headless','--path',$Root)+$A)){$i.ArgumentList.Add($x)};$p=[Diagnostics.Process]::new();$p.StartInfo=$i;try{if(!$p.Start()){throw "START:$N"};$o=$p.StandardOutput.ReadToEndAsync();$e=$p.StandardError.ReadToEndAsync();if(!$p.WaitForExit(900000)){$p.Kill($true);$p.WaitForExit();throw "TIMEOUT:$N"};$text=$o.GetAwaiter().GetResult()+$e.GetAwaiter().GetResult();[IO.File]::WriteAllText((Join-Path $Out "$N.log"),$text,$Utf8);if($p.ExitCode-ne 0-or$text-match$Fatal){throw "FAILED:$N"};Write-Host "$N=PASS";return $text}catch{throw}finally{$p.Dispose()}}
Identity 'identity-before.txt';$cache=Join-Path $Root '.godot';if(Test-Path $cache){Remove-Item $cache -Recurse -Force};RunG import @('--editor','--import')|Out-Null
$sample='res://tests/research/fabric_bake0/fabric_r5_5_successor_acceptance.gd'
$adv='res://tests/research/fabric_bake0/fabric_r5_5_adversarial_evidence.gd'
RunG parse @('--check-only','--script',$sample)|Out-Null;RunG parse @('--check-only','--script',$adv)|Out-Null
$payloads=@();1..3|%{$text=RunG "r55-acceptance-$_" @('--script',$sample);if($text -notmatch 'FABRIC_R5_5_RESULT=(\{.*\})'){throw 'R55_PAYLOAD_MISSING'};$payloads+=,$Matches[1]}
if(($payloads|Select-Object -Unique).Count -ne 1){throw 'R55_DETERMINISM_MISMATCH'};[IO.File]::WriteAllLines((Join-Path $Out 'r55-deterministic-payload.txt'),$payloads[0],$Utf8)
$atext=RunG 'r55-adversarial' @('--script',$adv);if($atext -notmatch 'FABRIC_R5_5_ADVERSARIAL=(\{.*\})'){throw 'R55_ADV_PAYLOAD_MISSING'};[IO.File]::WriteAllText((Join-Path $Out 'r55-adversarial-payload.txt'),$Matches[1],$Utf8)
&$PythonBin -c "import json,sys;d=json.load(open(sys.argv[1],encoding='utf-8'));sys.exit(0 if not d['failures'] else 1)" (Join-Path $Out 'r55-adversarial-payload.txt');if($LASTEXITCODE-ne 0){throw 'R55_ADV_CHECKS_FAILED'}
Write-Host 'R5_5_FOCUSED=PASS';Write-Host "EVIDENCE_DIR=$Out"
