extends "res://scripts/network/simulation/fixed_tick_input_buffer.gd"

# FIX10 carries the client prediction tick that is already present on the wire.
# It is semantic/ACK metadata, not an authority playout clock.
#
# FIX6 V1 and FIX7 V2 attempted to schedule server consumption from client_tick.
# That is unsafe because the client prediction clock can move forward during
# reconciliation and because the accepted parent queue can pressure-compact
# superseded continuous samples. A client_tick gap after either event is not a
# request to keep the old authority input active for that many server ticks.
# Treating it as one created a positive feedback loop: semantic wait -> pending
# backlog -> pressure compaction -> larger client_tick gap -> longer wait.
#
# FIX7b restores the pre-FIX6 realtime invariant: the accepted NX3/FIX4 input
# buffer selects the next available state transition on the nearest fixed server
# tick. Arrival cadence naturally preserves ordinary 30 Hz continuous holds on a
# 60 Hz server; jump edges and pressure recovery remain owned by the parent.
# client_tick is retained only to identify the authoritative post-input state.
const FIX10_INPUT_TIMELINE_POLICY: String = "PRESERVE_CLIENT_TICK_ON_CONSUMED_INPUT_V1"
# Legacy report identity retained for old FIX6 readers. This is no longer the
# effective server scheduling policy.
const FIX10_FIX6_SEMANTIC_SCHEDULE_POLICY: String = \
	"FIRST_APPLY_OFFSET_PRESERVES_CLIENT_TICK_SPACING_V1"
const FIX10_FIX7_EFFECTIVE_SEMANTIC_SCHEDULE_POLICY: String = \
	"RELATIVE_APPLIED_TICK_PRESERVES_CLIENT_SPACING_V2"
const FIX10_FIX7B_INPUT_PLAYOUT_POLICY: String = \
	"ARRIVAL_PACED_NEAREST_FIXED_TICK_CLIENT_TICK_METADATA_ONLY_V1"

var _fix10_current_client_tick: int = 0
var _fix10_current_input_applied_server_tick: int = 0
var _fix10_current_input_sequence: int = 0
var _fix10_consumed_with_client_tick: int = 0
var _fix10_missing_client_tick_metadata: int = 0

# Compatibility/diagnostic counters retained so existing report consumers do not
# break. Under FIX7b there is no semantic wait generated by client_tick.
var _fix10_fix6_client_to_server_tick_offset: int = 0
var _fix10_fix6_semantic_wait_ticks: int = 0
var _fix10_fix6_late_apply_events: int = 0
var _fix10_fix6_max_late_apply_ticks: int = 0
var _fix10_fix6_same_client_tick_compactions: int = 0
var _fix10_fix6_same_client_tick_inputs_dropped: int = 0
var _fix10_fix6_last_target_server_tick: int = 0
var _fix10_fix7_first_inputs_applied_immediately: int = 0
var _fix10_fix7_relative_targets: int = 0
var _fix10_fix7_max_future_wait_ticks: int = 0
var _fix10_fix7b_arrival_paced_consumes: int = 0
var _fix10_fix7b_max_queue_age_before_consume: int = 0


func configure(last_processed_sequence: int = 0) -> Dictionary:
	_fix10_current_client_tick = 0
	_fix10_current_input_applied_server_tick = 0
	_fix10_current_input_sequence = 0
	_fix10_consumed_with_client_tick = 0
	_fix10_missing_client_tick_metadata = 0
	_fix10_fix6_client_to_server_tick_offset = 0
	_fix10_fix6_semantic_wait_ticks = 0
	_fix10_fix6_late_apply_events = 0
	_fix10_fix6_max_late_apply_ticks = 0
	_fix10_fix6_same_client_tick_compactions = 0
	_fix10_fix6_same_client_tick_inputs_dropped = 0
	_fix10_fix6_last_target_server_tick = 0
	_fix10_fix7_first_inputs_applied_immediately = 0
	_fix10_fix7_relative_targets = 0
	_fix10_fix7_max_future_wait_ticks = 0
	_fix10_fix7b_arrival_paced_consumes = 0
	_fix10_fix7b_max_queue_age_before_consume = 0
	return super.configure(last_processed_sequence)


func consume_for_tick(server_tick: int) -> Dictionary:
	if server_tick < 1:
		return super.consume_for_tick(server_tick)

	# Snapshot metadata before the parent pops/compacts the winning entry.
	var client_tick_by_sequence: Dictionary = {}
	for queued_value in _pending:
		var queued: Dictionary = Dictionary(queued_value)
		var sequence: int = int(queued.get("input_sequence", 0))
		if sequence > 0:
			client_tick_by_sequence[sequence] = int(queued.get("client_tick", 0))
	_fix10_fix7b_max_queue_age_before_consume = maxi(
		_fix10_fix7b_max_queue_age_before_consume,
		_oldest_queue_age(server_tick)
	)

	# Critical FIX7b behavior: no client_tick-derived waiting. Let the accepted
	# realtime buffer consume the next available transition now.
	var result: Dictionary = super.consume_for_tick(server_tick)
	if not bool(result.get("success", false)):
		return result
	var details: Dictionary = Dictionary(result.get("details", {})).duplicate(true)
	if bool(details.get("consumed_new_input", false)):
		var sequence: int = int(details.get("input_sequence", 0))
		var client_tick: int = int(client_tick_by_sequence.get(sequence, 0))
		if client_tick > 0:
			var had_previous: bool = _fix10_current_client_tick > 0
			_fix10_current_client_tick = client_tick
			_fix10_current_input_applied_server_tick = server_tick
			_fix10_current_input_sequence = sequence
			_fix10_consumed_with_client_tick += 1
			_fix10_fix7b_arrival_paced_consumes += 1
			_fix10_fix6_client_to_server_tick_offset = server_tick - client_tick
			_fix10_fix6_last_target_server_tick = server_tick
			if not had_previous:
				_fix10_fix7_first_inputs_applied_immediately += 1
		else:
			_fix10_missing_client_tick_metadata += 1

	details["fix10_client_tick"] = _fix10_current_client_tick
	details["fix10_input_applied_server_tick"] = _fix10_current_input_applied_server_tick
	details["fix10_input_sequence"] = _fix10_current_input_sequence
	details["fix10_fix6_semantic_target_server_tick"] = server_tick
	details["fix10_fix6_client_to_server_tick_offset"] = _fix10_fix6_client_to_server_tick_offset
	details["fix10_fix7_effective_semantic_schedule_policy"] = \
		FIX10_FIX7_EFFECTIVE_SEMANTIC_SCHEDULE_POLICY
	details["fix10_fix7b_input_playout_policy"] = FIX10_FIX7B_INPUT_PLAYOUT_POLICY
	result["details"] = details
	return result


func get_report(server_tick: int = 0) -> Dictionary:
	var report: Dictionary = super.get_report(server_tick)
	report["fix10_input_timeline_policy"] = FIX10_INPUT_TIMELINE_POLICY
	report["fix10_current_client_tick"] = _fix10_current_client_tick
	report["fix10_current_input_applied_server_tick"] = _fix10_current_input_applied_server_tick
	report["fix10_current_input_sequence"] = _fix10_current_input_sequence
	report["fix10_consumed_with_client_tick"] = _fix10_consumed_with_client_tick
	report["fix10_missing_client_tick_metadata"] = _fix10_missing_client_tick_metadata
	report["fix10_fix6_semantic_schedule_policy"] = FIX10_FIX6_SEMANTIC_SCHEDULE_POLICY
	report["fix10_fix6_tick_offset_initialized"] = _fix10_current_client_tick > 0
	report["fix10_fix6_client_to_server_tick_offset"] = _fix10_fix6_client_to_server_tick_offset
	report["fix10_fix6_semantic_wait_ticks"] = _fix10_fix6_semantic_wait_ticks
	report["fix10_fix6_late_apply_events"] = _fix10_fix6_late_apply_events
	report["fix10_fix6_max_late_apply_ticks"] = _fix10_fix6_max_late_apply_ticks
	report["fix10_fix6_same_client_tick_compactions"] = _fix10_fix6_same_client_tick_compactions
	report["fix10_fix6_same_client_tick_inputs_dropped"] = _fix10_fix6_same_client_tick_inputs_dropped
	report["fix10_fix6_last_target_server_tick"] = _fix10_fix6_last_target_server_tick
	report["fix10_fix7_effective_semantic_schedule_policy"] = \
		FIX10_FIX7_EFFECTIVE_SEMANTIC_SCHEDULE_POLICY
	report["fix10_fix7_first_inputs_applied_immediately"] = \
		_fix10_fix7_first_inputs_applied_immediately
	report["fix10_fix7_relative_targets"] = _fix10_fix7_relative_targets
	report["fix10_fix7_max_future_wait_ticks"] = _fix10_fix7_max_future_wait_ticks
	report["fix10_fix7b_input_playout_policy"] = FIX10_FIX7B_INPUT_PLAYOUT_POLICY
	report["fix10_fix7b_arrival_paced_consumes"] = _fix10_fix7b_arrival_paced_consumes
	report["fix10_fix7b_max_queue_age_before_consume"] = \
		_fix10_fix7b_max_queue_age_before_consume
	return report
