extends SceneTree

const UtilsScript = preload("res://scripts/network/contracts/network_contract_utils.gd")
const Fixture = preload("res://tests/construction/fixtures/c13_runtime_projection_fixture.gd")
const SynchronizerScript = preload("res://scripts/construction/runtime_projection/construction_runtime_projection_synchronizer.gd")

var assertions := 0
var failures: Array[String] = []
var synchronizer

func _init() -> void:
	synchronizer = SynchronizerScript.new(); root.add_child(synchronizer)
	_test_static_mesh_collision_and_replay()
	_test_partial_rebuild_and_c11_path()
	_test_spatial_door_and_mobile_physics()
	_test_split_world_and_recovery()
	_finish()

func _test_static_mesh_collision_and_replay() -> void:
	var request := Fixture.beam_request("integration-beam", 0, 4.0, [12.0, 1.0, -3.0])
	var before_json := UtilsScript.canonical_json(request)
	var applied: Dictionary = synchronizer.upsert(request); _assert_ok(applied, "Static beam projection failed")
	var construct_id := String(request["construct_snapshot"]["construct_id"])
	var node = synchronizer.get_construct_node(construct_id)
	_assert(node != null and node is Node3D, "Runtime construct node missing")
	_assert(node.get_body() is StaticBody3D, "Static construct did not create StaticBody3D")
	_assert(node.position == Vector3(12.0, 1.0, -3.0), "Runtime construct world origin mismatch")
	var part_id := String(request["construct_snapshot"]["parts"][0]["part_id"])
	var part_node = node.get_part_node(part_id)
	_assert(part_node != null and part_node.get_child_count() == 1, "Beam visual node/mesh missing")
	_assert(part_node.get_child(0) is MeshInstance3D and part_node.get_child(0).mesh is BoxMesh, "Beam did not create BoxMesh")
	var collisions: Array = node.get_part_collision_nodes(part_id)
	_assert(collisions.size() == 1 and collisions[0] is CollisionShape3D, "Beam collision missing")
	_assert(collisions[0].shape is BoxShape3D, "Beam collision did not use BoxShape3D")
	_assert(collisions[0].get_parent() == node.get_body(), "CollisionShape3D is not direct child of PhysicsBody3D")
	_assert(UtilsScript.canonical_json(request) == before_json, "Presentation projection mutated authoritative request")
	var generation: int = synchronizer.get_generation(); var presentation_generation: int = synchronizer.get_presentation_generation(); var node_id: int = node.get_instance_id(); var part_node_id: int = part_node.get_instance_id()
	var replay: Dictionary = synchronizer.upsert(request); _assert_ok(replay, "Static projection replay failed")
	_assert(bool(replay["details"]["replay"]), "Static projection replay not marked")
	_assert(synchronizer.get_generation() == generation and synchronizer.get_presentation_generation() == presentation_generation, "Exact replay changed generations")
	_assert(synchronizer.get_construct_node(construct_id).get_instance_id() == node_id and synchronizer.get_construct_node(construct_id).get_part_node(part_id).get_instance_id() == part_node_id, "Exact replay rebuilt nodes")

func _test_partial_rebuild_and_c11_path() -> void:
	var initial := Fixture.two_beam_request("partial", false)
	_assert_ok(synchronizer.upsert(initial), "Two-part projection failed")
	var construct_id := String(initial["construct_snapshot"]["construct_id"]); var node = synchronizer.get_construct_node(construct_id)
	var first_id := "part/runtime/pair/partial/first"; var second_id := "part/runtime/pair/partial/second"
	var first_instance: int = node.get_part_node(first_id).get_instance_id(); var second_instance: int = node.get_part_node(second_id).get_instance_id(); var rebuild_before: int = node.get_rebuild_count()
	var updated: Dictionary = synchronizer.upsert(Fixture.two_beam_request("partial", true)); _assert_ok(updated, "Partial runtime update failed")
	node = synchronizer.get_construct_node(construct_id)
	_assert(node.get_part_node(first_id).get_instance_id() == first_instance, "Unchanged part was rebuilt")
	_assert(node.get_part_node(second_id).get_instance_id() != second_instance, "Changed part was not rebuilt")
	_assert(node.get_rebuild_count() == rebuild_before + 1, "Partial update rebuilt wrong number of parts")
	var apply_result: Dictionary = updated["details"]["apply_result"]["details"]
	_assert(apply_result["unchanged_part_ids"] == [first_id], "Partial update unchanged set mismatch")
	_assert(apply_result["rebuilt_part_ids"] == [second_id], "Partial update rebuilt set mismatch")
	var path_request := Fixture.edited_beam_request("path-integration", [0.0, 3.0, 0.0])
	_assert_ok(synchronizer.upsert(path_request), "C11 path projection failed")
	var path_node = synchronizer.get_construct_node(String(path_request["construct_snapshot"]["construct_id"]))
	var path_part_id := String(path_request["construct_snapshot"]["parts"][0]["part_id"]); var path_part = path_node.get_part_node(path_part_id)
	_assert(path_part.get_child_count() == 2, "C11 path did not create two mesh segments")
	_assert(path_part.get_child(0).get_child(0) is MeshInstance3D and path_part.get_child(1).get_child(0) is MeshInstance3D, "C11 path segment meshes missing")
	_assert(path_node.get_part_collision_nodes(path_part_id).size() == 2, "C11 path collision segment count mismatch")
	for collision in path_node.get_part_collision_nodes(path_part_id): _assert(collision.get_parent() == path_node.get_body(), "Path collision not attached directly to body")

func _test_spatial_door_and_mobile_physics() -> void:
	var closed_request := Fixture.house_request("integration-house", false, [20.0, 0.0, 0.0])
	var closed_json := UtilsScript.canonical_json(closed_request)
	_assert_ok(synchronizer.upsert(closed_request), "Closed house projection failed")
	var construct_id := String(closed_request["construct_snapshot"]["construct_id"]); var house = synchronizer.get_construct_node(construct_id)
	_assert(house.get_body() is StaticBody3D, "House did not create static physics body")
	var door_id := "part/spatial/integration-house/door"; var closed_door = house.get_part_node(door_id)
	_assert(String(closed_door.get_meta("opening_status")) == "CLOSED", "Closed door status not projected")
	_assert(absf(float(closed_door.get_meta("opening_target_angle_rad"))) < 0.000001, "Closed door angle not zero")
	var closed_link = house.get_opening_node("spatial-opening/main-door")
	_assert(closed_link is NavigationLink3D and not closed_link.enabled, "Closed door navigation link was enabled")
	_assert(closed_link.get_child_count() == 1 and closed_link.get_child(0) is Marker3D, "Door interaction anchor missing")
	var open_request := Fixture.house_request("integration-house", true, [20.0, 0.0, 0.0])
	_assert_ok(synchronizer.upsert(open_request), "Open house projection failed")
	house = synchronizer.get_construct_node(construct_id); var open_door = house.get_part_node(door_id)
	_assert(String(open_door.get_meta("opening_status")) == "OPEN", "Open door status not projected")
	_assert(absf(float(open_door.get_meta("opening_target_angle_rad")) - PI * 0.5) < 0.000001, "Open door angle not projected")
	_assert(absf(open_door.rotation.y) > 1.0, "Door transform did not rotate")
	var open_link = house.get_opening_node("spatial-opening/main-door")
	_assert(open_link is NavigationLink3D and open_link.enabled, "Open door navigation link was not enabled")
	_assert(bool(open_link.get_meta("interactive")) and String(open_link.get_meta("closure_part_id")) == door_id, "Opening interaction metadata mismatch")
	_assert(UtilsScript.canonical_json(closed_request) == closed_json, "Door projection mutated closed source snapshot")
	var rover_request := Fixture.rover_request("integration-rover", "healthy", [0.0, 0.0, 10.0])
	_assert_ok(synchronizer.upsert(rover_request), "Mobile rover projection failed")
	var rover = synchronizer.get_construct_node(String(rover_request["construct_snapshot"]["construct_id"])); var body = rover.get_body()
	_assert(body is RigidBody3D, "Mobile construct did not create RigidBody3D")
	_assert(not body.freeze, "Healthy rover rigid body is frozen")
	_assert(absf(body.mass - float(rover.get_descriptor()["total_mass_kg"])) < 0.000001, "Rover physics mass mismatch")
	var wheel_id := "part/mobile/integration-rover/wheel-fl"
	_assert(rover.get_part_node(wheel_id).get_child(0).mesh is CylinderMesh, "Wheel did not create CylinderMesh")
	_assert(rover.get_part_collision_nodes(wheel_id)[0].shape is CylinderShape3D, "Wheel did not create CylinderShape3D")
	_assert_ok(synchronizer.upsert(Fixture.rover_request("integration-rover", "immobile", [0.0, 0.0, 10.0])), "Immobile rover projection failed")
	rover = synchronizer.get_construct_node(String(rover_request["construct_snapshot"]["construct_id"])); body = rover.get_body()
	_assert(body is RigidBody3D and body.freeze, "Immobile rover body was not frozen")
	_assert(String(rover.get_descriptor()["mobility_state"]) == "IMMOBILE", "Immobile state not preserved")
	_assert(not rover.get_part_node(wheel_id).visible and rover.get_part_collision_nodes(wheel_id).is_empty(), "Destroyed wheel remained visible/colliding")

func _test_split_world_and_recovery() -> void:
	var before_requests := Fixture.split_world_before("integration")
	_assert_ok(synchronizer.sync_world(before_requests), "Pre-split world projection failed")
	var source_id := String(before_requests[0]["construct_snapshot"]["construct_id"]); var source = synchronizer.get_construct_node(source_id)
	var arm_id := "part/runtime/split/integration/arm"; var arm_item := "item/runtime/split/integration/arm"
	_assert(source.get_part_node(arm_id) != null, "Pre-split arm missing from source")
	var before_domain := UtilsScript.canonical_json(before_requests)
	var after_requests := Fixture.split_world_after("integration")
	var split: Dictionary = synchronizer.sync_world(after_requests); _assert_ok(split, "Split world projection failed")
	var child_id := String(after_requests[1]["construct_snapshot"]["construct_id"]); source = synchronizer.get_construct_node(source_id); var child = synchronizer.get_construct_node(child_id)
	_assert(source.get_part_node(arm_id) == null, "Split arm remained in source presentation")
	_assert(child != null and child.get_part_node(arm_id) != null, "Split arm missing from child presentation")
	_assert(String(child.get_part_node(arm_id).get_meta("item_instance_id")) == arm_item, "Split presentation changed item identity")
	_assert(synchronizer.get_construct_count() == 2, "Split world construct count mismatch")
	_assert(UtilsScript.canonical_json(before_requests) == before_domain, "Split synchronization mutated prior authoritative requests")
	var checksum: String = synchronizer.get_world_checksum(); var state: Dictionary = synchronizer.export_state(); var generation: int = synchronizer.get_generation()
	synchronizer.clear_presentation()
	_assert(synchronizer.get_construct_count() == 0 and synchronizer.get_generation() == generation, "Presentation clear changed descriptor authority")
	_assert_ok(synchronizer.rebuild_presentation(), "Presentation rebuild failed")
	_assert(synchronizer.get_construct_count() == 2 and synchronizer.get_world_checksum() == checksum, "Presentation rebuild diverged")
	var restored = SynchronizerScript.new(); root.add_child(restored); _assert_ok(restored.load_state(state), "Runtime synchronizer state load failed")
	_assert(restored.get_construct_count() == 2 and restored.get_world_checksum() == checksum, "Restored presentation diverged")
	var only_source := [after_requests[0]]; var removal: Dictionary = restored.sync_world(only_source); _assert_ok(removal, "Authoritative world removal failed")
	_assert(restored.get_construct_count() == 1 and restored.get_construct_node(child_id) == null, "Absent child construct was not removed")
	var duplicate_world := after_requests.duplicate(true)
	var duplicated_child: Dictionary = duplicate_world[1].duplicate(true); duplicated_child["construct_snapshot"] = Dictionary(duplicated_child["construct_snapshot"]).duplicate(true)
	duplicated_child["construct_snapshot"]["parts"][0]["item_instance_id"] = "item/runtime/split/integration/anchor"
	duplicated_child["construct_snapshot"]["checksum"] = preload("res://scripts/construction/contracts/construct_snapshot.gd").compute_checksum(duplicated_child["construct_snapshot"])
	duplicated_child["checksum"] = preload("res://scripts/construction/runtime_projection/construction_runtime_projection_request.gd").compute_checksum(duplicated_child)
	_assert_error(restored.sync_world([after_requests[0], duplicated_child]), "CONSTRUCTION_RUNTIME_WORLD_DUPLICATE_ITEM_ID", "Runtime world accepted duplicated item identity")

func _assert_ok(result: Dictionary, message: String) -> void: _assert(bool(result.get("success", false)), "%s: %s" % [message, result])
func _assert_error(result: Dictionary, expected: String, message: String) -> void: _assert(not bool(result.get("success", false)) and String(result.get("error_code", "")) == expected, "%s: %s" % [message, result])
func _assert(condition: bool, message: String) -> void:
	assertions += 1
	if not condition: failures.append(message)
func _finish() -> void:
	if failures.is_empty(): print("C13 runtime projection integration: PASS (%d assertions)" % assertions); quit(0); return
	for failure in failures: push_error(failure)
	print("C13 runtime projection integration: FAIL (%d failures, %d assertions)" % [failures.size(), assertions]); quit(1)
