extends SceneTree
const F=preload("res://tests/construction/fixtures/c17_distributed_authority_fixture.gd")
const Record=preload("res://scripts/construction/distributed/construction_authority_record.gd")
const Plan=preload("res://scripts/construction/distributed/construction_authority_migration_plan.gd")
const Cluster=preload("res://scripts/construction/distributed/construction_distributed_authority_cluster.gd")
const Registry=preload("res://scripts/construction/distributed/construction_authority_registry.gd")
const Persistence=preload("res://scripts/construction/distributed/construction_distributed_authority_persistence.gd")
const Transfer=preload("res://scripts/construction/distributed/construction_cross_zone_item_transfer.gd")
var assertions=0;var failures:Array[String]=[]
func _init():_scenario();_finish()
func _scenario():
 var a=F.FakeGateway.new();var b=F.FakeGateway.new();var c=F.FakeGateway.new();var registry=Registry.new();var cluster=Cluster.new();_ok(cluster.setup(registry),"setup")
 _ok(cluster.register_server(F.SERVER_A,F.CELL_A,a),"server a");_ok(cluster.register_server(F.SERVER_B,F.CELL_B,b),"server b");_ok(cluster.register_server(F.SERVER_C,F.CELL_C,c),"server c")
 _ok(cluster.set_tick(1),"tick 1");var initial=F.state();var record=F.record(String(initial.checksum));_ok(cluster.register_construct(record,initial),"register construct");_ok(cluster.register_replica(F.CONSTRUCT,F.SERVER_B),"replica b");_ok(cluster.register_replica(F.CONSTRUCT,F.SERVER_C),"replica c")
 _assert(not cluster.get_replica(F.CONSTRUCT,F.SERVER_B).can_write(),"replica write disabled")
 var cmd0=F.routed(0,F.SERVER_A,1,F.SERVER_B);var first=cluster.submit(F.SERVER_B,cmd0);_ok(first,"forward command");_assert(first.forwarded and first.owner_server_id==F.SERVER_A,"forward route");_assert(a.commit_count==1 and b.commit_count==0 and c.commit_count==0,"single owner commit")
 var after_first=registry.get_record(F.CONSTRUCT);_assert(after_first.construct_checksum==a.get_construct_checksum(F.CONSTRUCT),"record checksum refresh");_assert(cluster.get_replica(F.CONSTRUCT,F.SERVER_C).get_state().construct_checksum==after_first.construct_checksum,"replica sync")
 var replay=cluster.submit(F.SERVER_C,cmd0);_ok(replay,"forward replay");_assert(replay.gateway_result.replay,"gateway replay");_assert(a.commit_count==1,"replay duplicate commit")
 var wrong=F.routed(1,F.SERVER_B,1,F.SERVER_C);_err(cluster.submit(F.SERVER_C,wrong),"CONSTRUCTION_AUTHORITY_OWNER_MISMATCH","wrong owner");_assert(a.commit_count==1,"wrong owner changed state")
 var p=Plan.create("authority-migration/c17/a-to-b",F.CONSTRUCT,F.SERVER_A,F.SERVER_B,F.CELL_A,F.CELL_B,1,String(after_first.checksum),String(after_first.construct_checksum),[F.SERVER_A,F.SERVER_C],{"boundary":"east"})
 var begun=cluster.begin_migration(p);_ok(begun,"begin migration");_assert(registry.get_record(F.CONSTRUCT).state==Record.MIGRATING,"migration fence")
 _err(cluster.submit(F.SERVER_A,F.routed(2,F.SERVER_A,1,F.SERVER_A)),"CONSTRUCTION_AUTHORITY_MIGRATION_FENCED","write while fenced");_assert(a.commit_count==1,"fenced write committed")
 _ok(cluster.install_migration(begun.handoff),"install handoff");_ok(cluster.commit_migration(p,30),"commit migration");var moved=registry.get_record(F.CONSTRUCT);_assert(moved.owner_server_id==F.SERVER_B and moved.authority_epoch==2,"owner moved");_assert(b.get_construct_checksum(F.CONSTRUCT)==a.get_construct_checksum(F.CONSTRUCT),"handoff checksum")
 var old_replay=cluster.submit(F.SERVER_C,cmd0);_ok(old_replay,"cross epoch replay");_assert(bool(old_replay.get("cross_epoch_replay",false)) and old_replay.gateway_result.replay,"cross epoch replay marker");_assert(a.commit_count==1 and b.commit_count==0,"cross epoch replay duplicate")
 _err(cluster.submit(F.SERVER_A,F.routed(3,F.SERVER_A,1,F.SERVER_A)),"CONSTRUCTION_AUTHORITY_EPOCH_MISMATCH","stale epoch")
 var cmd3=F.routed(3,F.SERVER_B,2,F.SERVER_A);var moved_write=cluster.submit(F.SERVER_A,cmd3);_ok(moved_write,"post migration write");_assert(moved_write.forwarded and moved_write.owner_server_id==F.SERVER_B,"post migration route");_assert(b.commit_count==1 and a.commit_count==1,"post migration single commit")
 var current=registry.get_record(F.CONSTRUCT);_assert(cluster.get_replica(F.CONSTRUCT,F.SERVER_C).get_state().owner_server_id==F.SERVER_B,"replica owner update")
 var child_state=F.state(F.CHILD,"split-child");var child_record=Record.create(F.CHILD,F.SERVER_C,F.CELL_C,1,String(child_state.checksum),[F.SERVER_A],40,F.SERVER_C,{"parent_construct_id":F.CONSTRUCT})
 _ok(cluster.register_split_child(F.CONSTRUCT,child_record,child_state),"cross zone split child");_assert(registry.get_record(F.CHILD).owner_server_id==F.SERVER_C,"child owner")
 var child_write=cluster.submit(F.SERVER_B,F.routed(4,F.SERVER_C,1,F.SERVER_B,F.CHILD));_ok(child_write,"child routed write");_assert(c.commit_count==1,"child target commit");_assert(registry.get_record(F.CONSTRUCT).owner_server_id==F.SERVER_B,"parent owner preserved")
 var transfer=Transfer.create("cross-zone-transfer/c17/split-items","operation/c17/split-items",["item-instance/c17/arm","item-instance/c17/tool"],F.SERVER_B,F.SERVER_C,F.CELL_B,F.CELL_C,F.CONSTRUCT,F.CHILD,2,{"reason":"c9-split"});_ok(cluster.authorize_cross_zone_transfer(transfer),"cross zone item transfer");var wrong_transfer=transfer.duplicate(true);wrong_transfer.source_server_id=F.SERVER_A;wrong_transfer.checksum=Transfer.compute_checksum(wrong_transfer);_err(cluster.authorize_cross_zone_transfer(wrong_transfer),"CONSTRUCTION_CROSS_ZONE_TRANSFER_OWNER_MISMATCH","cross zone wrong owner")
 _ok(cluster.set_tick(30),"tick 30");_ok(cluster.set_server_available(F.SERVER_B,false),"owner fail");_err(cluster.takeover(F.CONSTRUCT,F.SERVER_C,30,60),"CONSTRUCTION_AUTHORITY_LEASE_NOT_EXPIRED","takeover before lease")
 _ok(cluster.set_tick(31),"tick 31");var takeover=cluster.takeover(F.CONSTRUCT,F.SERVER_C,31,70);_ok(takeover,"takeover");var taken=registry.get_record(F.CONSTRUCT);_assert(taken.owner_server_id==F.SERVER_C and taken.authority_epoch==3,"takeover epoch");_assert(c.get_construct_checksum(F.CONSTRUCT)==taken.construct_checksum,"takeover state")
 _err(cluster.submit(F.SERVER_A,F.routed(5,F.SERVER_B,2,F.SERVER_A)),"CONSTRUCTION_AUTHORITY_EPOCH_MISMATCH","old owner epoch after takeover")
 var post_takeover=cluster.submit(F.SERVER_A,F.routed(5,F.SERVER_C,3,F.SERVER_A));_ok(post_takeover,"post takeover write");_assert(c.commit_count==2,"takeover owner commit")
 _ok(cluster.set_server_available(F.SERVER_A,false),"entry a fail");_err(cluster.submit(F.SERVER_A,F.routed(6,F.SERVER_C,3,F.SERVER_A)),"CONSTRUCTION_AUTHORITY_ENTRY_SERVER_UNAVAILABLE","entry unavailable");_ok(cluster.set_server_available(F.SERVER_A,true),"entry a restore")
 var storage=F.MemoryStore.new();_ok(Persistence.save(storage,cluster),"save");var restored=Cluster.new();_ok(restored.setup(Registry.new()),"restore setup");_ok(restored.register_server(F.SERVER_A,F.CELL_A,a),"restore a");_ok(restored.register_server(F.SERVER_B,F.CELL_B,b),"restore b");_ok(restored.register_server(F.SERVER_C,F.CELL_C,c),"restore c");_ok(Persistence.load(storage,restored),"load");_assert(restored.get_registry().get_record(F.CONSTRUCT).checksum==registry.get_record(F.CONSTRUCT).checksum,"registry persistence");_assert(restored.get_replica(F.CONSTRUCT,F.SERVER_C).get_state().checksum==cluster.get_replica(F.CONSTRUCT,F.SERVER_C).get_state().checksum,"replica persistence")
 var persisted=cluster.export_state();var tampered=persisted.duplicate(true);tampered.tick=int(tampered.tick)+1;_err(restored.load_state(tampered),"CONSTRUCTION_DISTRIBUTED_AUTHORITY_STATE_CHECKSUM_MISMATCH","cluster state tamper")
 var replay_after_restore=restored.submit(F.SERVER_A,F.routed(5,F.SERVER_C,3,F.SERVER_A));_ok(replay_after_restore,"restored replay");_assert(replay_after_restore.gateway_result.replay and c.commit_count==2,"restored duplicate commit")
func _ok(r,m):_assert(bool(r.get("success",false)),"%s: %s"%[m,r])
func _err(r,c,m):_assert(not bool(r.get("success",false)) and String(r.get("error_code",""))==c,"%s: %s"%[m,r])
func _assert(v,m):assertions+=1;if not v:failures.append(m)
func _finish():
 if failures.is_empty():print("C17 distributed authority integration: PASS (%d assertions)"%assertions);quit(0);return
 for f in failures:push_error(f)
 print("C17 distributed authority integration: FAIL (%d failures, %d assertions)"%[failures.size(),assertions]);quit(1)
