extends SceneTree

const UtilsScript = preload("res://scripts/network/contracts/network_contract_utils.gd")
const FixtureScript = preload("res://tests/construction/fixtures/c8_fabrication_cell_fixture.gd")
const AdapterScript = preload("res://scripts/construction/item_graph/in_memory_construction_item_graph_adapter.gd")
const CatalogScript = preload("res://scripts/construction/fabrication/construction_fabrication_catalog.gd")
const QueueScript = preload("res://scripts/construction/fabrication/construction_fabrication_queue_store.gd")
const ProcessScript = preload("res://scripts/construction/fabrication/construction_fabrication_process.gd")
const MachineCompilerScript = preload("res://scripts/construction/fabrication/construction_fabrication_machine_compiler.gd")
const PlannerScript = preload("res://scripts/construction/fabrication/construction_fabrication_transaction_planner.gd")
const PersistenceScript = preload("res://scripts/construction/fabrication/construction_fabrication_persistence.gd")
const AgentScript = preload("res://scripts/construction/fabrication/construction_fabrication_agent.gd")
const PartScript = preload("res://scripts/construction/contracts/construction_part_record.gd")
const SnapshotScript = preload("res://scripts/construction/contracts/construct_snapshot.gd")
const BuildStageScript = preload("res://scripts/construction/build/construction_build_stage.gd")
const BuildPlanScript = preload("res://scripts/construction/build/construction_build_plan.gd")
const ProjectionScript = preload("res://scripts/construction/item_graph/construction_item_projection.gd")

class MemoryStore:
	extends RefCounted
	var states: Dictionary = {}
	func save_state(key: String, state: Dictionary) -> Dictionary:
		states[key] = state.duplicate(true)
		return {"success": true}
	func load_state(key: String) -> Dictionary:
		if not states.has(key): return {"success": false, "error_code": "STATE_NOT_FOUND"}
		return {"success": true, "state": Dictionary(states[key]).duplicate(true)}

var assertions := 0
var failures: Array[String] = []

func _init() -> void:
	_test_end_to_end_fabrication_and_build_plan()
	_test_power_block_and_resume()
	_test_cancel_and_release()
	_test_crash_reconcile_and_exact_replay()
	_test_agent_queue_and_recipe_pinning()
	_test_persistence_and_tamper_rejection()
	_finish()

func _new_runtime(key: String) -> Dictionary:
	var graph := FixtureScript.machine_item_graph(key)
	var adapter = AdapterScript.new(); _assert_ok(adapter.setup(graph.items, [graph.snapshot]), "Adapter setup failed")
	var catalog = CatalogScript.new(); _assert_ok(catalog.setup(), "Catalog setup failed")
	var recipe := FixtureScript.recipe(); _assert_ok(catalog.publish(recipe), "Recipe publish failed")
	var queue = QueueScript.new(); _assert_ok(queue.setup(), "Queue setup failed")
	var process = ProcessScript.new(); _assert_ok(process.setup(adapter, catalog, queue), "Process setup failed")
	var profile_result := MachineCompilerScript.compile(graph.snapshot, FixtureScript.machine_definition(key), FixtureScript.behavior_profile(key, graph.snapshot), FixtureScript.powered_spatial_profile("power-%s" % key))
	_assert_ok(profile_result, "Machine profile compile failed")
	return {"adapter": adapter, "catalog": catalog, "queue": queue, "process": process, "profile": profile_result.profile, "recipe": recipe, "snapshot": graph.snapshot}

func _enqueue(runtime: Dictionary, key: String, priority: int = 100) -> Dictionary:
	return runtime.process.enqueue_job("fabrication-job/%s" % key, "fabrication-recipe/structural-beam", 1, runtime.profile, FixtureScript.material_projections(key), {"beam": "item/fabricated/%s/beam" % key}, priority)

func _test_end_to_end_fabrication_and_build_plan() -> void:
	var rt := _new_runtime("e2e")
	var enqueued := _enqueue(rt, "e2e", 500)
	_assert_ok(enqueued, "Enqueue failed")
	_assert(String(enqueued.job.status) == "QUEUED", "Job not queued")
	_assert(int(rt.queue.get_generation()) == 1, "Queue generation after enqueue mismatch")
	var before_generation := int(rt.adapter.get_generation())
	var reserved: Dictionary = rt.process.reserve_job("fabrication-job/e2e", rt.profile)
	_assert_ok(reserved, "Reservation failed")
	_assert(String(reserved.job.status) == "RESERVED", "Job not reserved")
	_assert(int(rt.adapter.get_generation()) == before_generation + 1, "Reservation not one authoritative generation")
	var coolant: Dictionary = rt.adapter.get_item_projection("item/material/e2e/coolant")
	var steel: Dictionary = rt.adapter.get_item_projection("item/material/e2e/steel")
	_assert(String(coolant.relation.container_id) == String(rt.profile.input_container_id), "Coolant not reserved in machine input")
	_assert(String(steel.relation.container_id) == String(rt.profile.input_container_id), "Steel not reserved in machine input")
	_assert(int(coolant.revision) == 1 and int(steel.revision) == 1, "Reservation revisions mismatch")
	_assert(typeof(steel.components.batch_temperature_c) == TYPE_INT, "Adapter did not canonicalize integral float component")
	_assert(UtilsScript.canonical_json(steel.components) == UtilsScript.canonical_json({"grade": "S355", "batch_temperature_c": 100.0}), "Canonical fabrication input components changed")
	var machine: Dictionary = rt.adapter.get_construct_snapshot(String(rt.profile.construct_id))
	_assert(String(machine.compiled_facets.fabrication_runtime.active_job_id) == "fabrication-job/e2e", "Machine runtime missing active job")
	var first_progress: Dictionary = rt.process.advance_job("fabrication-job/e2e", rt.profile, 4, "operation/e2e/progress-1")
	_assert_ok(first_progress, "First progress failed")
	_assert(int(first_progress.job.work_completed) == 4, "First progress mismatch")
	var replay: Dictionary = rt.process.advance_job("fabrication-job/e2e", rt.profile, 4, "operation/e2e/progress-1")
	_assert_ok(replay, "Progress replay failed")
	_assert(bool(replay.replay), "Progress replay not detected")
	_assert(int(rt.queue.get_job("fabrication-job/e2e").work_completed) == 4, "Progress replay duplicated work")
	var final_progress: Dictionary = rt.process.advance_job("fabrication-job/e2e", rt.profile, 6, "operation/e2e/progress-2")
	_assert_ok(final_progress, "Final progress failed")
	_assert(int(final_progress.job.work_completed) == 10, "Final progress mismatch")
	var completed: Dictionary = rt.process.complete_job("fabrication-job/e2e", rt.profile)
	_assert_ok(completed, "Completion failed")
	_assert(String(completed.job.status) == "COMPLETED", "Job not completed")
	_assert(int(rt.adapter.get_generation()) == before_generation + 2, "Completion not one authoritative generation")
	_assert(rt.adapter.get_item_projection("item/material/e2e/coolant").is_empty(), "Exhausted coolant not consumed")
	steel = rt.adapter.get_item_projection("item/material/e2e/steel")
	_assert(int(steel.quantity) == 3, "Steel consumption mismatch")
	_assert(int(steel.revision) == 2, "Steel completion revision mismatch")
	var beam: Dictionary = rt.adapter.get_item_projection("item/fabricated/e2e/beam")
	_assert(not beam.is_empty(), "Fabricated beam missing")
	_assert(String(beam.definition_id) == "beam" and int(beam.quantity) == 1, "Fabricated beam identity mismatch")
	_assert(String(beam.relation.container_id) == String(rt.profile.output_container_id), "Fabricated beam output container mismatch")
	_assert(String(beam.components.fabrication_origin.job_id) == "fabrication-job/e2e", "Fabrication provenance missing job")
	_assert(String(beam.components.fabrication_origin.recipe_checksum) == String(rt.recipe.checksum), "Fabrication provenance missing recipe checksum")
	machine = rt.adapter.get_construct_snapshot(String(rt.profile.construct_id))
	_assert(String(machine.compiled_facets.fabrication_runtime.last_completed_job_id) == "fabrication-job/e2e", "Machine runtime missing completion")
	_assert(String(machine.compiled_facets.fabrication_runtime.active_job_id).is_empty(), "Machine runtime retained active job")
	_assert(int(machine.state_revision) == 2, "Machine revision did not advance twice")
	var part := PartScript.create("part/build/e2e/beam", String(beam.item_instance_id), "BEAM", "frame", 20.0, [0.0, 0.0, 0.0], {"fabricated": true})
	var target := SnapshotScript.create("construct/build/e2e", "item/build/e2e/root", 0, "OPERATIONAL", [part], [], {"operational": true, "capabilities": []})
	var stage := BuildStageScript.create("stage/build/e2e/operational", 0, "Install fabricated beam", "OPERATIONAL", [String(part.part_id)], [], [], ["INSTALL_COMPONENT"])
	var build_plan := BuildPlanScript.create("build-plan/e2e/fabricated-beam", "Fabricated beam assembly", ProjectionScript.world_relation(), target, [beam], [stage])
	_assert_ok(BuildPlanScript.validate(build_plan), "Fabricated output cannot enter C3 BuildPlan")
	_assert(String(build_plan.source_item_projections[0].item_instance_id) == String(beam.item_instance_id), "BuildPlan lost fabricated item identity")

func _test_power_block_and_resume() -> void:
	var rt := _new_runtime("power")
	_assert_ok(_enqueue(rt, "power"), "Power test enqueue failed")
	var offline_result := MachineCompilerScript.compile(rt.snapshot, FixtureScript.machine_definition("power"), FixtureScript.behavior_profile("power", rt.snapshot), FixtureScript.unpowered_spatial_profile("power-power"))
	_assert_ok(offline_result, "Offline profile compile failed")
	var state_before: Dictionary = rt.adapter.export_state()
	var blocked: Dictionary = rt.process.reserve_job("fabrication-job/power", offline_result.profile)
	_assert_error(blocked, "FABRICATION_MACHINE_NOT_ONLINE", "Offline machine reserved inputs")
	_assert(String(rt.queue.get_job("fabrication-job/power").status) == "BLOCKED", "Offline job not marked blocked")
	_assert(UtilsScript.canonical_json(rt.adapter.export_state()) == UtilsScript.canonical_json(state_before), "Offline reservation changed Item Graph")
	var resumed: Dictionary = rt.process.reserve_job("fabrication-job/power", rt.profile)
	_assert_ok(resumed, "Powered machine did not resume blocked job")
	_assert(String(resumed.job.status) == "RESERVED", "Resumed job not reserved")
	var progress_blocked: Dictionary = rt.process.advance_job("fabrication-job/power", offline_result.profile, 2, "operation/power/offline-progress")
	_assert_error(progress_blocked, "FABRICATION_MACHINE_OFFLINE", "Offline machine advanced work")
	_assert(int(rt.queue.get_job("fabrication-job/power").work_completed) == 0, "Offline progress changed work")
	var progress: Dictionary = rt.process.advance_job("fabrication-job/power", rt.profile, 10, "operation/power/progress")
	_assert_ok(progress, "Powered progress failed")
	_assert_ok(rt.process.complete_job("fabrication-job/power", rt.profile), "Powered completion failed")

func _test_cancel_and_release() -> void:
	var rt := _new_runtime("cancel")
	_assert_ok(_enqueue(rt, "cancel"), "Cancel enqueue failed")
	_assert_ok(rt.process.reserve_job("fabrication-job/cancel", rt.profile), "Cancel reserve failed")
	var reserved_steel: Dictionary = rt.adapter.get_item_projection("item/material/cancel/steel")
	_assert(String(reserved_steel.relation.container_id) == String(rt.profile.input_container_id), "Cancel input not reserved")
	var cancelled: Dictionary = rt.process.cancel_job("fabrication-job/cancel", rt.profile)
	_assert_ok(cancelled, "Cancel failed")
	_assert(String(cancelled.job.status) == "CANCELLED", "Job not cancelled")
	var steel: Dictionary = rt.adapter.get_item_projection("item/material/cancel/steel")
	var coolant: Dictionary = rt.adapter.get_item_projection("item/material/cancel/coolant")
	_assert(String(steel.relation.container_id) == "container/raw/cancel", "Cancel did not restore steel")
	_assert(String(coolant.relation.container_id) == "container/raw/cancel", "Cancel did not restore coolant")
	_assert(int(steel.quantity) == 6 and int(coolant.quantity) == 1, "Cancel changed material quantities")
	_assert(rt.adapter.get_item_projection("item/fabricated/cancel/beam").is_empty(), "Cancel created output")
	var machine: Dictionary = rt.adapter.get_construct_snapshot(String(rt.profile.construct_id))
	_assert(String(machine.compiled_facets.fabrication_runtime.last_cancelled_job_id) == "fabrication-job/cancel", "Cancel runtime missing job")

func _test_crash_reconcile_and_exact_replay() -> void:
	var rt := _new_runtime("crash")
	_assert_ok(_enqueue(rt, "crash"), "Crash enqueue failed")
	_assert_ok(rt.process.reserve_job("fabrication-job/crash", rt.profile), "Crash reserve failed")
	_assert_ok(rt.process.advance_job("fabrication-job/crash", rt.profile, 10, "operation/crash/progress"), "Crash progress failed")
	var job: Dictionary = rt.queue.get_job("fabrication-job/crash")
	var machine_before: Dictionary = rt.adapter.get_construct_snapshot(String(rt.profile.construct_id))
	var inputs := [rt.adapter.get_item_projection("item/material/crash/coolant"), rt.adapter.get_item_projection("item/material/crash/steel")]
	var planned := PlannerScript.build_completion_plan("plan/fabrication/crash/complete", "operation/fabrication/crash/complete", machine_before, job, rt.recipe, inputs, String(rt.profile.output_container_id))
	_assert_ok(planned, "Crash completion plan failed")
	var committed: Dictionary = rt.adapter.apply_plan(planned.plan)
	_assert_ok(committed, "Crash authoritative completion failed")
	_assert(String(rt.queue.get_job("fabrication-job/crash").status) == "PROCESSING", "Crash simulation unexpectedly updated queue")
	var reconciled: Dictionary = rt.process.reconcile_job("fabrication-job/crash")
	_assert_ok(reconciled, "Crash reconcile failed")
	_assert(String(reconciled.job.status) == "COMPLETED", "Crash reconcile did not complete job")
	_assert(not rt.adapter.get_item_projection("item/fabricated/crash/beam").is_empty(), "Crash output missing")
	var generation := int(rt.adapter.get_generation())
	var replay: Dictionary = rt.adapter.apply_plan(planned.plan)
	_assert_ok(replay, "Exact completion replay failed")
	_assert(int(rt.adapter.get_generation()) == generation, "Exact completion replay advanced generation")
	_assert(String(replay.plan_checksum) == String(committed.plan_checksum), "Exact completion replay changed result")
	_assert(int(rt.adapter.export_state().items.filter(func(i): return String(i.item_instance_id) == "item/fabricated/crash/beam").size()) == 1, "Crash replay duplicated output")

func _test_agent_queue_and_recipe_pinning() -> void:
	var rt := _new_runtime("agent")
	_assert_ok(_enqueue(rt, "agent", 900), "Agent enqueue failed")
	var v2 := FixtureScript.recipe(2)
	_assert_ok(rt.catalog.publish(v2), "Recipe v2 publish failed")
	_assert(int(rt.catalog.latest_version("fabrication-recipe/structural-beam")) == 2, "Catalog did not advance recipe")
	_assert(int(rt.queue.get_job("fabrication-job/agent").recipe_version) == 1, "Queued job recipe version changed")
	var agent = AgentScript.new(); _assert_ok(agent.setup(rt.process, rt.queue, ["OPERATE_FABRICATION_CELL"]), "Agent setup failed")
	var executed: Dictionary = agent.execute_next(rt.profile)
	_assert_ok(executed, "Agent execution failed")
	_assert(String(rt.queue.get_job("fabrication-job/agent").status) == "COMPLETED", "Agent did not complete job")
	var output: Dictionary = rt.adapter.get_item_projection("item/fabricated/agent/beam")
	_assert(String(output.components.fabrication_origin.recipe_checksum) == String(rt.recipe.checksum), "Agent used unpinned recipe version")
	var no_work: Dictionary = agent.execute_next(rt.profile)
	_assert_ok(no_work, "Agent no-work check failed")
	_assert(bool(no_work.no_work), "Agent did not report empty queue")
	var unskilled = AgentScript.new()
	_assert_error(unskilled.setup(rt.process, rt.queue, []), "CONSTRUCTION_FABRICATION_AGENT_CAPABILITY_REQUIRED", "Unskilled agent accepted")

func _test_persistence_and_tamper_rejection() -> void:
	var rt := _new_runtime("persist")
	_assert_ok(_enqueue(rt, "persist"), "Persistence enqueue failed")
	_assert_ok(rt.process.reserve_job("fabrication-job/persist", rt.profile), "Persistence reserve failed")
	_assert_ok(rt.process.advance_job("fabrication-job/persist", rt.profile, 5, "operation/persist/progress"), "Persistence progress failed")
	var memory = MemoryStore.new()
	var persistence = PersistenceScript.new(); _assert_ok(persistence.setup(rt.catalog, rt.queue, memory, "fabrication-c8"), "Persistence setup failed")
	var saved: Dictionary = persistence.save(); _assert_ok(saved, "Persistence save failed")
	_assert(String(saved.checksum).length() == 64, "Persistence checksum invalid")
	var catalog2 = CatalogScript.new(); catalog2.setup()
	var queue2 = QueueScript.new(); queue2.setup()
	var persistence2 = PersistenceScript.new(); _assert_ok(persistence2.setup(catalog2, queue2, memory, "fabrication-c8"), "Restart persistence setup failed")
	_assert_ok(persistence2.load(), "Persistence load failed")
	_assert(UtilsScript.canonical_json(catalog2.to_dict()) == UtilsScript.canonical_json(rt.catalog.to_dict()), "Catalog persistence changed")
	_assert(UtilsScript.canonical_json(queue2.to_dict()) == UtilsScript.canonical_json(rt.queue.to_dict()), "Queue persistence changed")
	_assert(String(queue2.get_job("fabrication-job/persist").status) == "PROCESSING", "Persisted job status mismatch")
	_assert(int(queue2.get_job("fabrication-job/persist").work_completed) == 5, "Persisted job progress mismatch")
	var tampered: Dictionary = memory.states["fabrication-c8"].duplicate(true)
	tampered.queue.jobs[0].work_completed = 9
	memory.states["fabrication-c8"] = tampered
	var catalog3 = CatalogScript.new(); catalog3.setup()
	var queue3 = QueueScript.new(); queue3.setup()
	var persistence3 = PersistenceScript.new(); persistence3.setup(catalog3, queue3, memory, "fabrication-c8")
	_assert_error(persistence3.load(), "CONSTRUCTION_FABRICATION_JOB_CHECKSUM_MISMATCH", "Persistence accepted tampered job")
	_assert(catalog3.list_recipes().is_empty() and queue3.list_jobs().is_empty(), "Rejected persistence mutated domain")

func _assert_ok(result: Dictionary, message: String) -> void: _assert(bool(result.get("success", false)), "%s: %s" % [message, result])
func _assert_error(result: Dictionary, code: String, message: String) -> void: _assert(not bool(result.get("success", false)) and String(result.get("error_code", "")) == code, "%s: %s" % [message, result])
func _assert(condition: bool, message: String) -> void: assertions += 1; if not condition: failures.append(message)
func _finish() -> void:
	if failures.is_empty(): print("C8 fabrication cell integration: PASS (%d assertions)" % assertions); quit(0); return
	for failure in failures: push_error(failure)
	print("C8 fabrication cell integration: FAIL (%d failures, %d assertions)" % [failures.size(), assertions]); quit(1)
