extends RefCounted
## COMPLEX3 research source: canonical addressable parts are generated by a frozen recipe.
## The source stores an expanded streaming digest, but never materializes all records at once.
const U = preload("res://scripts/research/fabric_bake0/fabric_bake_contract_utils_v1.gd")
const SourceRevision = preload("res://scripts/simulation/representation/contracts/representation_source_revision.gd")
const Frontier = preload("res://scripts/research/fabric_bake0/canonical_source_frontier_v1.gd")
const AuthorityEnvelope = preload("res://scripts/research/fabric_bake0/authority_envelope_v1.gd")
const H = preload("res://scripts/research/fabric_bake0/bridge3_rigid_handoff_v1.gd")

const SCHEMA := "planet_simulator.fabric_complex3_streaming_structure.v1"
const AGGREGATE_SCHEMA := "planet_simulator.fabric_complex3_streaming_aggregate.v1"
const GENERATOR_VERSION := "FABRIC_COMPLEX3_STREAMING_R1"
const REGION_SIZE := 20
const OWNER_ID := "server/complex3"
const DEPENDENCY_HASH := "5fffb94d5a67af97b0c91501dd4971ad0a95198f895915fe75c21aed012bb20a"
const ALLOWED_COUNTS := [5000, 20000, 100000]

static func part_id(index: int) -> String:
	return "part/complex3-%06d" % index
static func bond_id(index: int) -> String:
	return "bond/complex3-%06d" % index
static func region_id(index: int) -> String:
	return "region/complex3-%06d" % (index / REGION_SIZE)
static func break_index(count: int) -> int:
	return count / 2 + 7
static func target_region_start(count: int) -> int:
	return (break_index(count) / REGION_SIZE) * REGION_SIZE

static func create_subject(count: int, broken: bool = false) -> Dictionary:
	if not ALLOWED_COUNTS.has(count): return U.failure("COMPLEX3_SCALE_NOT_AUTHORIZED")
	var bindex := break_index(count)
	var spec := {"schema": SCHEMA, "generator_version": GENERATOR_VERSION,
		"construct_id": "construct/complex3-%06d" % count, "part_count": count,
		"bond_count": count - 2 if broken else count - 1, "region_size": REGION_SIZE,
		"region_count": (count + REGION_SIZE - 1) / REGION_SIZE, "source_revision": 1 if broken else 0,
		"break_index": bindex, "break_bond_id": bond_id(bindex), "broken_bond_id": bond_id(bindex) if broken else "",
		"expanded_part_digest": _expanded_part_digest(count), "expanded_bond_digest": _expanded_bond_digest(count, bindex if broken else -1), "checksum": ""}
	spec.checksum = U.compute_checksum(spec)
	var matter_payload := {"matter_id": "matter/complex3-%06d" % count,
		"material_family": "RIGID_COMPLEX3_STREAMING_TEST_MATTER", "material_revision": 0}
	var construction := SourceRevision.create("CONSTRUCTION", spec.construct_id, 9, 1000 + count + int(spec.source_revision), U.canonical_hash(spec), DEPENDENCY_HASH)
	var matter := SourceRevision.create("MATTER", matter_payload.matter_id, 9, 10, U.canonical_hash(matter_payload), DEPENDENCY_HASH)
	var frontier := Frontier.create([matter, construction])
	var authority := _authority(frontier)
	return {"success": true, "spec": spec, "construction": construction, "matter": matter,
		"frontier": frontier, "authority": authority, "matter_payload": matter_payload}

static func validate_subject(subject: Dictionary, rederive_expanded_digests: bool = false) -> Dictionary:
	if subject.get("success") != true or typeof(subject.get("spec")) != TYPE_DICTIONARY: return U.failure("COMPLEX3_INVALID_SUBJECT")
	var spec: Dictionary = subject.spec
	var required := ["schema", "generator_version", "construct_id", "part_count", "bond_count", "region_size", "region_count",
		"source_revision", "break_index", "break_bond_id", "broken_bond_id", "expanded_part_digest", "expanded_bond_digest", "checksum"]
	if spec.keys().size() != required.size(): return U.failure("COMPLEX3_SPEC_FIELDS_INVALID")
	for field in required:
		if not spec.has(field): return U.failure("COMPLEX3_SPEC_FIELDS_INVALID")
	if spec.schema != SCHEMA or spec.generator_version != GENERATOR_VERSION or not ALLOWED_COUNTS.has(int(spec.part_count)): return U.failure("COMPLEX3_SPEC_IDENTITY_INVALID")
	if not U.validate_checksum(spec).success: return U.failure("COMPLEX3_SPEC_CHECKSUM_INVALID")
	var count := int(spec.part_count); var broken := not String(spec.broken_bond_id).is_empty()
	if int(spec.region_size) != REGION_SIZE or int(spec.break_index) != break_index(count) or String(spec.break_bond_id) != bond_id(break_index(count)): return U.failure("COMPLEX3_SPEC_TOPOLOGY_INVALID")
	if int(spec.source_revision) != (1 if broken else 0): return U.failure("COMPLEX3_SPEC_REVISION_INVALID")
	if int(spec.bond_count) != count - (2 if broken else 1): return U.failure("COMPLEX3_SPEC_BOND_COUNT_INVALID")
	if broken and String(spec.broken_bond_id) != String(spec.break_bond_id): return U.failure("COMPLEX3_SPEC_BREAK_INVALID")
	if rederive_expanded_digests:
		if spec.expanded_part_digest != _expanded_part_digest(count): return U.failure("COMPLEX3_PART_DIGEST_MISMATCH")
		if spec.expanded_bond_digest != _expanded_bond_digest(count, int(spec.break_index) if broken else -1): return U.failure("COMPLEX3_BOND_DIGEST_MISMATCH")
	if not Frontier.validate(subject.get("frontier", {})).success or not AuthorityEnvelope.validate_b0_safety(subject.get("authority", {})).success: return U.failure("COMPLEX3_SOURCE_BINDING_INVALID")
	return U.success()

static func is_successor(previous: Dictionary, current: Dictionary) -> bool:
	if not validate_subject(previous, false).success or not validate_subject(current, false).success: return false
	if int(previous.spec.part_count) != int(current.spec.part_count) or int(previous.spec.source_revision) != 0 or int(current.spec.source_revision) != 1: return false
	if previous.spec.expanded_part_digest != current.spec.expanded_part_digest or String(current.spec.broken_bond_id) != String(previous.spec.break_bond_id): return false
	return int(current.construction.source_revision) == int(previous.construction.source_revision) + 1

static func part_model(index: int) -> Dictionary:
	var mass := _mass(index); var half := _half_extents(index); var size := half * 2.0
	return {"part_id": part_id(index), "region_id": region_id(index), "index": index, "mass": mass,
		"position": H.a(_position(index)), "orientation": [0.0, 0.0, 0.0, 1.0],
		"inertia_tensor": [[mass * (size.y * size.y + size.z * size.z) / 12.0, 0.0, 0.0],
			[0.0, mass * (size.x * size.x + size.z * size.z) / 12.0, 0.0],
			[0.0, 0.0, mass * (size.x * size.x + size.y * size.y) / 12.0]]}

static func aggregate_span(spec: Dictionary, first: int, end_exclusive: int) -> Dictionary:
	var count := int(spec.get("part_count", -1))
	if first < 0 or end_exclusive > count or first >= end_exclusive: return U.failure("COMPLEX3_INVALID_SPAN")
	var total_mass := 0.0; var weighted := Vector3.ZERO
	var ixx_o := 0.0; var iyy_o := 0.0; var izz_o := 0.0; var ixy_o := 0.0; var ixz_o := 0.0; var iyz_o := 0.0
	for index in range(first, end_exclusive):
		var m := _mass(index); var p := _position(index); var half := _half_extents(index); var size := half * 2.0
		var ixx_l := m * (size.y * size.y + size.z * size.z) / 12.0
		var iyy_l := m * (size.x * size.x + size.z * size.z) / 12.0
		var izz_l := m * (size.x * size.x + size.y * size.y) / 12.0
		total_mass += m; weighted += p * m
		ixx_o += ixx_l + m * (p.y * p.y + p.z * p.z); iyy_o += iyy_l + m * (p.x * p.x + p.z * p.z); izz_o += izz_l + m * (p.x * p.x + p.y * p.y)
		ixy_o += -m * p.x * p.y; ixz_o += -m * p.x * p.z; iyz_o += -m * p.y * p.z
	var com := weighted / total_mass
	var ixx := ixx_o - total_mass * (com.y * com.y + com.z * com.z); var iyy := iyy_o - total_mass * (com.x * com.x + com.z * com.z); var izz := izz_o - total_mass * (com.x * com.x + com.y * com.y)
	var ixy := ixy_o + total_mass * com.x * com.y; var ixz := ixz_o + total_mass * com.x * com.z; var iyz := iyz_o + total_mass * com.y * com.z
	var result := {"schema": AGGREGATE_SCHEMA, "source_checksum": spec.checksum, "first_part": first, "end_exclusive": end_exclusive,
		"part_count": end_exclusive - first, "total_mass": total_mass, "center_of_mass": H.a(com),
		"inertia_tensor_body": [[ixx, ixy, ixz], [ixy, iyy, iyz], [ixz, iyz, izz]],
		"span_hash": U.canonical_hash({"source_checksum": spec.checksum, "first": first, "end": end_exclusive}), "checksum": ""}
	result.checksum = U.compute_checksum(result)
	return U.success({"descriptor": result, "parts_scanned": end_exclusive - first})

static func reference_state() -> Dictionary:
	return {"position": [104.25, -87.5, 32.125], "orientation": [0.0349778888017522, 0.174889444008761, -0.0524668332026284, 0.982339451384805],
		"linear_velocity": [4.75, -1.25, 0.625], "angular_velocity": [0.35, -0.17, 0.22]}
static func local_part_state(parent_state: Dictionary, parent_com: Array, index: int) -> Dictionary:
	return H.shift(parent_state, H.a(_position(index) - H.v(parent_com)))
static func span_state(parent_state: Dictionary, parent_com: Array, descriptor: Dictionary) -> Dictionary:
	return H.shift(parent_state, H.a(H.v(descriptor.center_of_mass) - H.v(parent_com)))
static func part_position(index: int) -> Array:
	return H.a(_position(index))

static func _expanded_part_digest(count: int) -> String:
	var context := HashingContext.new(); context.start(HashingContext.HASH_SHA256)
	for index in range(count): context.update(U.canonical_hash(part_model(index)).to_utf8_buffer())
	return context.finish().hex_encode()
static func _expanded_bond_digest(count: int, skipped_index: int) -> String:
	var context := HashingContext.new(); context.start(HashingContext.HASH_SHA256)
	for index in range(1, count):
		if index == skipped_index: continue
		context.update(U.canonical_hash({"bond_id": bond_id(index), "part_a": part_id(index - 1), "part_b": part_id(index), "rigid": true}).to_utf8_buffer())
	return context.finish().hex_encode()
static func _mass(index: int) -> float: return 1.0 + 0.025 * float(index % 11)
static func _half_extents(index: int) -> Vector3: return Vector3(0.35 + 0.015 * float(index % 3), 0.28 + 0.010 * float(index % 5), 0.22 + 0.012 * float(index % 7))
static func _position(index: int) -> Vector3:
	var x := index % 10; var y := (index / 10) % 10; var z := index / 100
	return Vector3((float(x) - 4.5) * 1.25, (float(y) - 4.5) * 1.10, (float(z) - 2.0) * 0.95)
static func _authority(frontier: Dictionary) -> Dictionary:
	var records: Array = []; var mutable: Array = []
	for source in frontier.sources:
		records.append({"source_domain": source.source_domain, "source_id": source.source_id, "authority_epoch": source.authority_epoch, "owner_id": OWNER_ID})
		mutable.append(U.source_key(source.source_domain, source.source_id))
	return AuthorityEnvelope.create(OWNER_ID, records, mutable)
