extends SceneTree
const Slot = preload("res://scripts/research/fabric_bake0/bridge3_execution_slot_v1.gd")
const Fixture = preload("res://tests/research/fabric_bake0/fabric_bake_complex0_fixture.gd")
const U = preload("res://scripts/research/fabric_bake0/fabric_bake_contract_utils_v1.gd")
var checks := 0
func check(value: bool, label: String) -> void:
	checks += 1
	if not value:
		push_error("BRIDGE3-A: " + label)
		quit(1)
func _initialize() -> void:
	var f := Fixture.build(500)
	var source_hash := U.canonical_hash(f)
	var cell := Slot.new()
	check(cell.start(f.frontier, f.authority, "FULL", {"x": [1.0, 2.0]}).success, "start")
	check(not cell.start(f.frontier, f.authority, "FULL", {}).success, "double start")
	var before := cell.writer()
	var p := cell.prepare("operation/first", "STRUCTURAL_BAKE", {"x": [3.0]}, 1, f.frontier)
	check(p.success, "prepare")
	check(cell.writer() == before, "prepare has no publication")
	check(cell.snapshot().mode == "FULL", "one old owner while preparing")
	check(not cell.prepare("operation/other", "FULL", {}, 2, f.frontier).success, "competing preparation")
	check(cell.prepare("operation/first", "STRUCTURAL_BAKE", {"x": [3.0]}, 1, f.frontier).details.ticket == p.details.ticket, "repeat preparation")
	var committed := cell.commit(p.details.ticket, f.frontier)
	check(committed.success and committed.details.applied, "commit")
	check(cell.snapshot().transition_count == 1 and cell.snapshot().transition_epoch == 1, "epoch")
	check(cell.snapshot().mode == "STRUCTURAL_BAKE", "new owner")
	check(not cell.commit(p.details.ticket, f.frontier).details.applied, "exactly once")
	check(cell.prepare("operation/first", "STRUCTURAL_BAKE", {"x": [3.0]}, 1, f.frontier).details.already_committed, "repeat operation")
	check(not cell.prepare("operation/first", "FULL", {}, 2, f.frontier).success, "conflicting operation")
	check(not cell.accept_physical_state(before, {"x": [4.0]}, 2, f.frontier).success, "old writer fenced")
	check(not cell.commit("forged", f.frontier).success, "unknown ticket")
	var observed := cell.snapshot()
	observed.payload.x[0] = 900.0
	check(cell.snapshot().payload.x[0] == 3.0, "copy isolation")
	var pending := cell.prepare("operation/second", "FULL", {"x": [4.0]}, 3, f.frontier)
	check(pending.success, "prepare before physical write")
	check(cell.accept_physical_state(cell.writer(), {"x": [3.5]}, 2, f.frontier).success, "physical write")
	check(not cell.commit(pending.details.ticket, f.frontier).success, "stale prepared physical state")
	for invalid in [NAN, INF, -1.0, "tick", true]:
		check(not cell.prepare("operation/invalid", "FULL", {}, invalid, f.frontier).success, "bad tick")
	check(not cell.prepare("operation/nan", "FULL", {"x": NAN}, 4, f.frontier).success, "nonfinite payload")
	check(not cell.prepare("operation/unknown", "unknown", {}, 4, f.frontier).success, "unknown mode")
	var tampered: Dictionary = f.frontier.duplicate(true)
	tampered.frontier_hash = "0".repeat(64)
	check(not cell.can_execute(tampered), "tampered frontier")
	cell.invalidate()
	check(not cell.can_execute(f.frontier) and cell.writer().is_empty(), "immediate stale fencing")
	check(U.canonical_hash(f) == source_hash, "canonical source not mutated")
	print("BRIDGE3_A_HASH=" + U.canonical_hash(cell.snapshot()))
	print("FABRIC BRIDGE-3-A: PASS (%d assertions)" % checks)
	quit(0)
